export const GameConstant = {
  GAME_WIDTH  : 1920,
  GAME_HEIGHT : 1080,

  GAME_CODE                 : "PurusGames:TrafficRun",
  DEBUG_ORBIT_CAMERA        : 0,
  DEBUG_RENDER_PATH_POINT   : 0,
  DEBUG_RENDER_ATTACK_RANGE : 0,
  DEBUG_UNLOCK_ALL_SLOT     : 0,
  DEBUG_AMMO                : 0,

  SCENE_PLAY       : "PlayScene",
  SCENE_SHOP       : "ShopScene",
  SCENE_TRANSITION : "TransitionScene",

  UI_LAYER_MAIN            : "UIMainLayer",
  UI_LAYER_POPUP           : "PopupLayer",
  UI_LAYER_ADS             : "AdsLayer",
  UI_LAYER_UNLOCK_PLANT    : "UnlockPlantLayer",
  UI_LAYER_PLANT_SHOP      : "PlantShopLayer",
  UI_LAYER_BUY_SLOT_SCREEN : "BuySlotScreenLayer",
  UI_LAYER_TUTORIAL        : "TutorialLayer",

  UI_3D_LAYER_ID       : 33,
  SNOW_EFFECT_LAYER_ID : 34,
  GAMEPLAY_UI_LAYER_ID : 35,
  UI_STENCIL_LAYER_ID  : 36,

  ADS_SCREEN_NAME                      : "AdsScreen",
  CONTINUE_SCREEN_NAME                 : "ContinueScreen",
  CURRENCY_SCREEN_NAME                 : "CurrencyScreen",
  TUTORIAL_SCREEN_NAME                 : "TutorialScreen",
  PAUSE_SCREEN_NAME                    : "PauseScreen",
  LOADING_SCREEN_NAME                  : "LoadingScreen",
  SETTING_SCREEN_NAME                  : "SettingScreen",
  PLAY_SCREEN_NAME                     : "PlayScreen",
  HOME_SCREEN_NAME                     : "HomeScreen",
  SHOP_SCREEN_NAME                     : "ShopScreen",
  WIN_SCREEN_NAME                      : "WinScreen",
  LOSE_SCREEN_NAME                     : "LoseScreen",
  REWARD_SCREEN_NAME                   : "RewardScreen",
  WARNING_SCREEN_NAME                  : "WarningScreen",
  DAILY_CHALLENGE_SCREEN_NAME          : "DailyChallengeScreen",
  SETTING_IN_GAME_SCREEN_NAME          : "SettingInGameScreen",
  CHALLENGE_LEVEL_SELECTOR_SCREEN_NAME : "ChallengeLevelSelectorScreen",
  TAP_ZONE_SCREEN_NAME                 : "TapZoneScreen",
  LOSE_SCREEN_CHALLENGE_NAME           : "LoseScreenChallenge",
  MODE_SELECTOR_SCREEN_NAME            : "StartScreen",
  WAITING_SCREEN_NAME                  : "WaitingScreen",

  GAME_FONT_FIRA_SANS_BOLD    : "FiraSans-Bold",
  GAME_FONT_FIRA_SANS_REGULAR : "FiraSans-Regular",
  GAME_FONT_POPPINS_BOLD      : "font_poppins-bold",
  GAME_FONT_POPPINS_REGULAR   : "font_poppins-regular",
  GAME_FONT_POPPINS_SEMIBOLD  : "font_poppins-semiBold",

  GAME_FONT_NOTOSANS_BLACK        : "NotoSans-Black",
  GAME_FONT_NOTOSANS_ARABIC_BLACK : "NotoSansArabic-Black",
  GAME_FONT_NOTOSERIF_THAI        : "NotoSerifThai-Black",
  GAME_FONT_NOTOSANS_JP_BLACK     : "NotoSansJP-Black",
  GAME_FONT_NOTOSANS_SC_BLACK     : "NotoSansSC-Black",
  GAME_FONT_NOTOSANS_KR_BLACK     : "NotoSansKR-Black",

  STORAGE_CLEAR_ON_START               : 0,
  STORAGE_KEY_SETTING                  : "setting",
  STORAGE_SOUND_EFFECT                 : "soundEffect",
  STORAGE_PLAYER_LIFE                  : "playerLife",
  STORAGE_ENEMY_LIFE                   : "enemyLife",
  STORAGE_WEAPONS_UNLOCKED             : "weaponsUnlocked",
  STORAGE_SKINS_UNLOCKED               : "skin_unlocked",
  STORAGE_PLAYER_STATS                 : "playerStats",
  STORAGE_WEAPON_ACTIVE                : "weaponsActive",
  STORAGE_SKIN_ACTIVE                  : "skinActive",
  STORAGE_CURRENT_GAME_PROGRESS_DATA   : "currentGameProgressData",
  STORAGE_PLAYER_CONFIG                : "playerConfig",
  STORAGE_CURRENT_SKIN                 : "currentSkin",
  STORAGE_CURRENCY                     : "currency",
  STORAGE_HIGHEST_UNLOCKED_PLANT_LEVEL : "highestUnlockedPlantLevel",
  STORAGE_PLANT_BUY_COUNT              : "plantBuyCount",
  STORAGE_PLANT_LAYOUT                 : "plantLayout",
  STORAGE_SLOT_UNLOCK_SAVE_DATA        : "slotUnlockSaveData",
  STORAGE_TUTORIAL_DATA                : "tutorialData",
  STORE_BEST_STAGE_DAMAGE              : "bestStageDamage",
  STORAGE_KEY_LANGUAGE                 : "language",
  STORAGE_LAST_PLAY_TIME               : "lastPlayTime",
  STORAGE_PROGRESS_REWARD_SKIN         : "progressRewardSkin",
  STORAGE_CURRENT_LEVEL                : "currentLevel",
  STORAGE_KEY_TUTORIAL_COMPLETED       : "tutorialCompleted",
  STORAGE_GAME_TUTORIAL                : "gameTutorial",
  STORAGE_COMPLETED_TUTORIALS          : "completedTutorials",

  GAME_SETTING_KEY: {
    VIBRATION : "vibration",
    SOUND     : "sound",
    MUSIC     : "music",
  },

  ANIMATION_DURATION : 0.25,
  DURATION_DIALOG    : 0.2,
  GAME_RESIZE_RATIO  : 0.98,

  MAGAZINE: 10,

  FIXED_DELTA_TIME: 1 / 60,


  CAMERA_X                 : 0,
  CAMERA_Y                 : 25,
  CAMERA_Z                 : 38,
  CAMERA_X_LANDSCAPE       : 0,
  CAMERA_Y_LANDSCAPE       : 16,
  CAMERA_Z_LANDSCAPE       : 25,
  CAMERA_ROTATE_X          : -30,
  CAMERA_ROTATE_Y          : 0,
  CAMERA_ROTATE_Z          : 0,
  HIGHEST_PLANT_LEVEL      : 60,
  START_PLANT_ADS_AT_LEVEL : 6,
  OFFLINE_EARNING_RATIO    : 0.2,
  MIN_OFFLINE_TIME         : 300,
  MAX_OFFLINE_TIME         : 86400,

  LOSE_STAGE_REWARD_RATIO: 0.2,

  ENEMY_SLOW_SPEED_MULTIPLIER : 0.5,
  ENEMY_SLOW_DURATION         : 2,
  ENEMY_STUN_DURATION         : 2,

  MAX_STAGE_CHAPTER : 10,
  MAX_LEVEL         : 5,


  CHANGE_DIRECTION_TAG : "changeDirection",
  START_POINT_TAG      : "startPoint",
  GROUND_TAG           : "ground",
  FINISH_POINT_TAG     : "finishPoint",
  CAR_OBSTACLE_TAG     : "carObstacle",
  WATER_TAG            : "water",
  JUMP_TAG             : "jump",
  OBSTACLE_TAG         : "obstacle",
  POINT_OBSTACLE_TAG   : "poinObstacle",

  FIXED_TIME_STEP: 1 / 60,

  GRAVITY_X : 0,
  GRAVITY_Y : -9.8,
  GRAVITY_Z : 0,

  TARGET_FPS: 60,

  START_POINT_CAR_OBSTACLE_TAG : "startPointCarObstacle",
  END_POINT_CAR_OBSTACLE_TAG   : "endPointCarObstacle",
  CHANGE_DIRECTION_CAR_TAG     : "changeDirectionCar",

  USER_DATA_DEFAULT_SKIN      : "skin_01",
  TUTORIAL_SKIN               : "skin_02",
  USER_DATA_DEFAULT_CAR_MODEL : "model_car_01",

  DEFAULT_GET_CURRENCY_BY_ADS: 500,

  SPEED_TRAIN_OBSTACLE : 25,
  SPEED_CAR_OBSTACLE   : 5,

  FOG_DISTANCE_START_PORTRAIT : 60,
  FOG_DISTANCE_END_PORTRAIT   : 100,

  FOG_DISTANCE_START_LANDSCAPE : 35,
  FOG_DISTANCE_END_LANDSCAPE   : 100,

  PROGRESS_VALUE_INCREASE : 0.34,
  TOTAL_CAR_SKINS         : 18,
  CURRENCY_PER_BY_COLLIDE : 10,

  DURATION_SPAWN_CAR_OBSTACLE: 4,
} as const;
